parameters:
  ContainerRegistryAdminUser: ''
  ContainerRegistryPassword: ''

jobs:
- job: BuildAndPublishContainers
  steps:
  # Build and publish the NCS.AzureDevOpsAgents.OWASP docker image
  - template: AzureDevOpsTemplates/Build/StepTemplates/dfc-docker-publish-k8smanifest.yml@dfc-devops
    parameters:
      ContainerRegistryAdminUser: ${{ parameters.ContainerRegistryAdminUser }}
      ContainerRegistryPassword: ${{ parameters.ContainerRegistryPassword }}
      DockerfileContext: Linux/Owasp
      DockerfileName: Dockerfile
      ImageBaseName: NCS.AzureDevOpsAgents.OWASP
      ImageTag: $(Build.BuildNumber)
      ManifestFilePath: manifest.yml